import type { JSX, PropsWithChildren } from 'react';
import Header from './Header.tsx';
import styles from './app.module.css';

function App({ children }: PropsWithChildren): JSX.Element {
  return (
    <>
      <Header sxHeader={styles.header} sxInput={styles.input} />
      <main className={styles.main}>
        <nav className={styles.sidebar}>
          <ul className={styles.sidebarList}>
            <li>
              <span>Home</span>
            </li>
            <li>
              <span>Profile</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Contact</span>
            </li>
            <li>
              <span>Last</span>
            </li>
          </ul>
        </nav>
        <div className={styles.content}>{children}</div>
      </main>
      <footer className={styles.footer}>
        <p>© 2025</p>
        <p>All rights reserved.</p>
      </footer>
    </>
  );
}

export default App;
